Fix: detecting when a db driver is missing
ploomber/jupysql pull request #127
Opened 2023-02-09 23:10 UTC by tonykploomber

## Describe your changes

## Issue ticket number and link
Closes #x

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-02-14 01:28 UTC, tonykploomber commented
Hi @edublancas 

Two things need to confirm with you:
1. Do you think I can still use the `UsageError` class to [present the error message](https://github.com/ploomber/jupysql/pull/127/files#diff-62741718c66525b0e94e4021ad561835184c9d1c00e2a12c00cb6c33346cabd4R170)?
I tried to use `ModuleNotFoundError` with our error message, however, it will show the trace of error execution in detail

2023-02-14 01:40 UTC, tonykploomber commented
2. In current implementation, some existing test cases will fail

Those are in `src/tests/test_magic.py`

1. test_error_on_invalid_connection_string_format:
`%sql something://`
2. test_error_on_invalid_connection_string_with_possible_typo:
`%sql sqlite://`

Actually they are throwed by `sqlalchemy.create_engine`, since `sqlite` and `something` driver are not existing.

I think we should update the original test case, to except the user will see the `UsageError` with `To fix it, try to install the missing module` message, 

What do you think?

2023-02-14 01:41 UTC, tonykploomber commented
Also please check the way how I maintain the [missing package dict](https://github.com/ploomber/jupysql/pull/127/files#diff-62741718c66525b0e94e4021ad561835184c9d1c00e2a12c00cb6c33346cabd4R14), if you think this approach is doable I can go ahead with other common drivers

2023-02-14 12:18 UTC, edublancas commented
> Do you think I can still use the UsageError class to [present the error message](https://github.com/ploomber/jupysql/pull/127/files#diff-62741718c66525b0e94e4021ad561835184c9d1c00e2a12c00cb6c33346cabd4R170)?

Yeah, I think we can use UsageError, just do `raise UsageError(...) from e`, where e is the original exception. Python doesn't like it when you raise an exception while handling another exception

> Although the challenging part is: how do we know the driver namesomething is just the typo or there is a real missing driver not installed

we should keep a mapping of the most popular drivers (we can use the ones listed in sqlalchemy's documentation) and only display the "install package X" when there is a perfect match.

If there isn't a perfect match, we should let the other error show (the one I added here https://github.com/ploomber/jupysql/pull/120). Perhaps we can add to the generic message a "perhaps you meant to use X package?" and re-use the existing mapping. e.g.:

```
%sql dockdb://
```

```
Perhaps you meant duckdb?
```

to get similar matches, you can use: https://docs.python.org/3/library/difflib.html#difflib.get_close_matches

2023-02-14 12:19 UTC, edublancas requested changes

2023-02-14 12:19 UTC, edublancas commented on src/sql/connection.py
> +MISSING_PACKAGE_LIST_EXCEPT_MATCHERS = {
yeah, this makes sense. 

why does duckdb contain `sqlalchemy.dialects` but the other doesn't? is this just how sqlalchemy displays the error?

2023-02-14 23:19 UTC, tonykploomber commented
2/14 Update:

Progress:
- Add suggestion text for driver name is perfect matching -> imply driver is not installed, suggest user to install
- Add suggestion text for driver name is typo -> imply the typo, suggest user to type correct name

Block:
I was having a difficult time to simulate the package is not installed in unit-test phase.
For some driver, I faced some error when mocking some drivers weren't installed.

Tried to mock the missing package per:
- https://stackoverflow.com/a/60229056
- https://stackoverflow.com/questions/63865618/how-to-remove-a-library-with-monkeypatch-or-mock-in-pytest

None of those seems to work, our test cases will still be impacted by my system pip installed package.

I suggest moving this testing part into integration testing since we can manipulate the system environment on the container level

Will give the update soon

2023-02-15 23:31 UTC, edublancas requested changes
looks good, just one small change to make the error message clearer:

change:

```
UsageError: Can't load plugin: sqlalchemy.dialects:dockdb

To fix it, perhaps you meant to use driver name: duckdb

For technical support: https://ploomber.io/community
Documentation: https://jupysql.ploomber.io/en/latest/connecting.html
```

to:

```
UsageError: Can't load plugin: sqlalchemy.dialects:dockdb

Perhaps you meant to use the dialect: duckdb?

For technical support: https://ploomber.io/community
Documentation: https://jupysql.ploomber.io/en/latest/connecting.html
```

2023-02-16 15:40 UTC, tonykploomber commented
error message clearer
fix in [930022a](https://github.com/ploomber/jupysql/pull/127/commits/930022ad93e85b12cbe8c49c83e8fde97e1c8ee6)

2023-02-16 19:19 UTC, edublancas commented on CHANGELOG.md
> +* [Feature] Shows missing driver package suggestion message ([#124](https://github.com/ploomber/jupysql/issues/124))
FYI: there's no need to add the link manually. our deployment link takes care of it. just do (#NUMBER)

2023-02-16 19:19 UTC, edublancas approved these changes

2023-02-16 19:19 UTC, merged