testing duckdb-engine rc
ploomber/jupysql pull request #220
Opened 2023-03-08 00:09 UTC by edublancas

## Describe your changes

## Issue ticket number and link
Closes #x

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-03-08 02:44 UTC, Mause requested changes

2023-03-08 02:44 UTC, Mause commented on .github/workflows/ci-integration-db.yaml
> +          pip install git+https://github.com/Mause/duckdb_engine@v0.7.0-rc1
```suggestion
          pip install duckdb_engine==v0.7.0-rc1 --pre
```

2023-03-08 02:44 UTC, Mause commented on .github/workflows/ci.yaml
> +          pip install git+https://github.com/Mause/duckdb_engine@v0.7.0-rc1
```suggestion
          pip install duckdb_engine==v0.7.0-rc1 --pre
```

2023-03-08 23:27 UTC, edublancas commented
hey @Mause: I added your suggestion on how to install the release candidate but some tests failed.

however, the error seems unrelated to duckdb-engine

```
 FAILED src/tests/test_plot.py::test_boxplot_stats - duckdb.HTTPException: HTTP Error: HTTP Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/ab9736bed0/osx_amd64/sqlite_scanner.duckdb_extension.gz"
Extension "sqlite_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
FAILED src/tests/test_plot.py::test_boxplot_stats_exception - duckdb.HTTPException: HTTP Error: HTTP Error: Failed to download extension "sqlite_scanner" at URL "http://extensions.duckdb.org/ab9736bed0/osx_amd64/sqlite_scanner.duckdb_extension.gz"
Extension "sqlite_scanner" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```


But running the CI from a clean copy from the main branch didn't break: https://github.com/ploomber/jupysql/pull/224

any thoughts?

2023-03-13 13:35 UTC, edublancas commented
hi @mause: we found an issue with our fixed for sqlalchemy 2 compatibility (https://github.com/ploomber/jupysql/issues/234); so currently that's blocking us from testing this

2023-04-07 19:56 UTC, edublancas commented
hey @Mause, apologies for the long delay. we assigned sqlalchemy 2 compatibility to a contractor, but I didn't finish the job, so we assigned to somebody else in our team, and we just merged it. I see you released duckdb-engine 0.7 already, and our CI is passing with that version, so all good!

2023-04-07 19:56 UTC, closed without merging