change persistence
ploomber/jupysql pull request #244
Opened 2023-03-14 22:53 UTC by Palashio

## Describe your changes

## Issue ticket number and link
Closes #154 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-03-15 02:56 UTC, edublancas requested changes

2023-03-15 13:48 UTC, tonykploomber commented on src/sql/magic.py
> +            raise ValueError("You cannot both replace and append to a dataframe.")
Let's add the test case to catch this `ValueError`!

2023-03-15 15:55 UTC, Palashio commented on src/tests/integration/test_duckDB.py
> +    assert any("weather" == table[0] for table in out)
it's just the result of using the `black` formatter.

2023-03-15 15:56 UTC, Palashio commented on src/tests/test_magic.py
> +
Will change it to make it more clear; but doesn't what I've written do the same thing? If the last line returns an error, the test case will error out.

2023-03-15 16:40 UTC, edublancas commented
the docs failed but looks like it was an issue in the building system, so I re-trigger a build

2023-03-15 21:18 UTC, tonykploomber submitted a review, later dismissed

2023-03-16 01:31 UTC, edublancas requested changes
pleas rebase to solve file conflicts

2023-03-16 03:02 UTC, edublancas requested changes
looks good. please update the docs:

here, we can show a --persist-replace example:

https://jupysql.ploomber.io/en/latest/integrations/pandas.html?highlight=persist#uploading-a-dataframe-to-the-database

here, we need to document it:

https://jupysql.ploomber.io/en/latest/api/magic-sql.html?highlight=persist#sql-sql

(release version will be 0.6.6)

2023-03-17 00:28 UTC, edublancas commented
> @Palashio please add a changelog entry ([API Change])

this should be [Feature]  since we are adding something new, and not breaking anything

2023-03-17 14:41 UTC, tonykploomber commented
Downgrade the sqlalchemy might fix the CI issue

2023-03-19 04:18 UTC, closed without merging