postgres integration improvements
ploomber/jupysql pull request #259
Opened 2023-03-16 18:14 UTC by gtduncan

## Describe your changes
1. Moved `postgres-connect` tutorial to `integrations`
2. Migrated pgspecial commands to `postgres-connect`
3. Documented how to install pgspecial

## Issue ticket number and link
Closes #218 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-03-18 13:55 UTC, neelasha23 commented on doc/api/configuration.md
> -
There are some occurences of `shape: (0, 0)` in this doc. This looks incorrect?

2023-03-18 14:06 UTC, neelasha23 commented on doc/integrations/postgres-connect.ipynb
> +    "For reference, `psql`-style \\\"backslash\\\" [meta-commands](https://www.postgresql.org/docs/9.6/static/app-psql.html#APP-PSQL-META-COMMANDS) commands (``\\\\d``, ``\\\\dt``, etc.) are provided
This doesn't look very clear. Please add a better example if possible

2023-03-18 14:08 UTC, neelasha23 commented
Please convert the `integrations/postgres-connect.ipynb` file to `.md` format : `jupytext postgres-connect.ipynb --to myst`

2023-03-21 16:27 UTC, gtduncan commented
> Please convert the `integrations/postgres-connect.ipynb` file to `.md` format : `jupytext postgres-connect.ipynb --to myst`

When I worked on this, it was an `.ipynb` file with pre-existing executed outputs and was excluded from running in `conf.py` to preserve the outputs. I'm assuming this is due to the docker code cells needing to have already been run, so if I convert it to a `.md` file, these outputs are lost. Should I still convert it to `.md`? If I exclude it from running in `conf.py` then, no output at all is displayed, and otherwise, it gives the error:

`docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

2023-03-21 22:24 UTC, edublancas commented
you're right @gtduncan: let's keep it as an ipynb to  keep the outputs since we cannot run this in the docs building process

2023-03-21 22:44 UTC, edublancas requested changes
A few suggestions:

Rename: Get a PostgreSQL instance -> PostgreSQL

[Rename](https://jupysql--259.org.readthedocs.build/en/259/integrations/postgres-connect.html#postgresql-features): PostgreSQL features -> Executing meta-commands. Also, please add some more detail in such section "in order to run meta-commands, you can install pgspecial ..." and also link to the section in postgres-install where we explain how to install pgspecial, the section must also be moved before the "Clean up" section

2023-03-23 00:08 UTC, edublancas approved these changes

2023-03-23 00:09 UTC, merged