#286 document the %sqlcmd profile
ploomber/jupysql pull request #395
Opened 2023-04-12 08:45 UTC by chuwpeng123

## Describe your changes
Document the %sqlcmd profile command 

## Issue number

Closes #286 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--395.org.readthedocs.build/en/395/

2023-04-12 08:47 UTC, chuwpeng123 commented
@edublancas I think I have finished most of the documentation. However, for the output argument, I am not sure which file path I should specify and leave without an example here. Please let me know if it needs change.

2023-04-12 23:27 UTC, edublancas requested changes

2023-04-12 23:27 UTC, edublancas commented on doc/api/magic-profile.md
> +# `%sqlcmd profile`
```suggestion
# `%sqlcmd profile`

`%sqlcmd profile` allows you to summarize a table quickly.
```

2023-04-12 23:27 UTC, edublancas commented on doc/api/magic-profile.md
> +:tags: [hide-output]
```suggestion
```

Let's not hide the output since it's useful for the user. Usually, we hide it when it's very long and distracting

2023-04-12 23:28 UTC, edublancas commented
> @edublancas I think I have finished most of the documentation. However, for the output argument, I am not sure which file path I should specify and leave without an example here. Please let me know if it needs change.

You can put a generic path like `penguins-profile.html`

2023-04-26 19:50 UTC, edublancas requested changes

2023-04-26 19:50 UTC, edublancas commented on doc/api/penguins-profile.html
> +<table>
do not include this file in the repo, please delete

2023-04-28 19:45 UTC, closed without merging