Oracle Integration testing
ploomber/jupysql pull request #477
Opened 2023-05-03 02:52 UTC by tonykploomber

## Describe your changes

## Issue number

Closes #X

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-05-03 09:21 UTC, tonykploomber commented
Not sure why facing the error: `Can't load plugin: sqlalchemy.dialects:oracle.oracledb`

2023-05-03 14:44 UTC, tonykploomber commented
@yafimvo 
Hey yafim,

1. Can you help me to test our new Oracle DB container can be running on your windows environment?
2. I am facing some `sqlalchemy.exc.NoSuchModuleError` on our CI, but I don't have this issue on the local?

Once you start the oracle container, you can connect by SQLalchemy by

```
from sqlalchemy import create_engine, text

import oracledb
import pandas as pd
from sql import _testing
engine = create_engine(_testing._get_database_url("oracle"))
engine.connect()

```

to test if the oracle is ready

2023-05-03 16:51 UTC, yafimvo commented
@tonykploomber 


> * Can you help me to test our new Oracle DB container can be running on your windows environment?
> * I am facing some `sqlalchemy.exc.NoSuchModuleError` on our CI, but I don't have this issue on the local? Can you check this if possible?

I was able to run this [oracle container](https://hub.docker.com/r/gvenzl/oracle-xe), and use this code to connect to it without errors. tested on Windows 11.

Please note that initially, it takes about ~10 seconds after the container is up to successfully connect to it.

2023-05-15 14:49 UTC, tonykploomber commented
@yafimvo 
Do you remember any extra steps you did in the Windows environment to make Oracle run?
If yes, can you help me to update the doc with that?

2023-05-15 14:53 UTC, tonykploomber commented
@idomic @yafimvo 
Pardon for the delay due to doc building issue in CI, the related discussion [was here](https://ploomber-internal.slack.com/archives/C03DRTB87HB/p1683267456104559)

The solution is to add `oracle.ipynb` file in `doc/conf.py` in `nb_execution_excludepatterns` section to skip the execution build process

2023-05-17 11:03 UTC, yafimvo requested changes
added some notes

2023-05-23 09:56 UTC, tonykploomber commented on doc/connecting.md
> +- [Oracle](integrations/oracle)
Added in https://jupysql--477.org.readthedocs.build/en/477/connecting.html#tutorials

2023-05-23 09:57 UTC, tonykploomber commented on doc/integrations/oracle.ipynb
> +    "%sql --with saved_cte SELECT * FROM saved_cte"
Done

https://jupysql--477.org.readthedocs.build/en/477/integrations/oracle.html

![Uploading Screenshot 2023-05-23 at 5.57.15 PM.png…]()

2023-05-23 09:59 UTC, tonykploomber commented on doc/integrations/oracle.ipynb
> +    "threshold = 6.0"
It's referring from [Postgresql](https://jupysql--477.org.readthedocs.build/en/477/integrations/postgres-connect.html#parametrize-queries) doc

I guess the purpose is to demonstrate different variable value will display different query result.

But I agree with you, addressed and removed the second threshold part in oracledoc

2023-05-23 09:59 UTC, tonykploomber commented on doc/integrations/oracle.ipynb
> +    "List columns in the taxi table:"
Done

2023-05-23 09:59 UTC, tonykploomber commented on doc/integrations/oracle.ipynb
> +    "Now, let's start JuppySQL, authenticate and start querying the data!"
Good catch, done

2023-05-23 10:00 UTC, tonykploomber commented on doc/integrations/oracle.ipynb
> +    "Now, let's fetch some sample data. We'll be using the [NYC taxi dataset](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page):"
Fix taxi -> iris

2023-05-23 10:00 UTC, tonykploomber commented
Please review again! Thanks

2023-05-23 10:14 UTC, yafimvo approved these changes
lgtm.

My only concern is that we are using a [non-official oracle image](https://jupysql--477.org.readthedocs.build/en/477/integrations/oracle.html#start-oracle-instance).

@idomic what do you think?

2023-05-26 15:01 UTC, merged

2023-05-26 15:02 UTC, edublancas commented
let's see how it goes, if the non-official image gives trouble, we can remove the integration tests and only keep the user guide