Product analytics tutorial
ploomber/jupysql pull request #485
Opened 2023-05-09 17:37 UTC by neelasha23

## Describe your changes
Tutorial on product analytics

## Issue number

Closes #264 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--485.org.readthedocs.build/en/485/

2023-05-24 12:13 UTC, neelasha23 commented
Reference PR: https://github.com/ploomber/jupysql/pull/321/files

2023-05-24 15:04 UTC, lfunderburk commented
Ok, will review today @neelasha23

2023-05-24 20:17 UTC, edublancas requested changes

2023-05-24 20:17 UTC, edublancas commented on doc/tutorials/product-analytics.md
> +| 3      | 5 |3|5|
can we remove this sample table and add a cell that produces this output?

2023-05-24 20:17 UTC, edublancas commented on doc/tutorials/product-analytics.md
> +| 2      | 4 |3|5|
can we remove this sample table and add a cell that produces this output?

2023-05-24 20:17 UTC, edublancas commented on doc/tutorials/product-analytics.md
> +# Product Analytics Using JupySQL
```suggestion
# Product Analytics
```

2023-05-24 20:17 UTC, edublancas commented
please fix merging conflicts

2023-05-25 20:10 UTC, edublancas approved these changes

2023-05-25 20:10 UTC, merged