Atexit2
ploomber/jupysql pull request #551
Opened 2023-05-30 19:54 UTC by TegveerG

## Describe your changes

Created new branch with updated pull (no reverts to existing files). 
Code same as before (#547) 

## Issue number

Closes #458 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-05-30 22:06 UTC, edublancas commented
is this ready for review? you're missing unit tests for the close connections function

2023-05-30 22:24 UTC, TegveerG commented
> is this ready for review? you're missing unit tests for the close connections function

Hi, adding unit test and pushing a final commit. Not ready for review yet.

2023-05-30 22:58 UTC, TegveerG commented
@edublancas ready for review!

2023-05-31 13:30 UTC, edublancas requested changes
coincidentally, another PR already implemented a `close_all` function that's been unit tested so for this PR you only need to add the `atexit.register` line

2023-05-31 13:30 UTC, edublancas commented on src/tests/test_connection.py
> +def test_close_all_connections(cleanup):
also, please fix the merging conflicts

2023-05-31 22:30 UTC, closed without merging