Added test and example for -c/--creator feature
ploomber/jupysql pull request #567
Opened 2023-06-01 10:34 UTC by DaveOkpare

## Describe your changes

Added test and example for -c/--creator feature

## Issue number

Closes #131 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-06-01 13:57 UTC, edublancas requested changes

2023-06-01 13:57 UTC, edublancas commented on doc/api/magic-sql.md
> +## Specify creator function
according to the [docs](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.creator), creator must be a function that returns a DBAPI connection:

```
In [11]: engine = create_engine("sqlite://", creator=lambda:sqlite3.connect(""))

In [12]: engine.execute('SELECT name FROM sqlite_schema WHERE type=\'table\' ORDER BY name;')
Out[12]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x103531840>

In [13]: engine.execute('SELECT name FROM sqlite_schema WHERE type=\'table\' ORDER BY name;').fetchall()
Out[13]: []
```

please update the examples and the test.

2023-06-06 15:48 UTC, edublancas commented on doc/api/magic-sql.md
> +## Specify creator function
yeah, I got the same error. probably an issue on duckdb's end, please add an example with sqlite as I showed in the previous comment

2023-06-06 17:58 UTC, edublancas requested changes
check your code, it's failing due to a listing problem

2023-06-07 12:40 UTC, DaveOkpare commented
> check your code, it's failing due to a linting problem

@edublancas Thanks for the heads up, I made too many commits before reading the linting logs, should I open a new pull request to make things cleaner?

2023-06-07 16:55 UTC, edublancas requested changes
no need to open a new PR. just  ensure all tests pass

2023-06-07 16:55 UTC, edublancas commented on doc/api/magic-sql.md
> +%sql --creator engine
the docs are failing bc the `engine` variable doesn't exist

2023-06-07 20:33 UTC, edublancas approved these changes

2023-06-07 20:33 UTC, merged

2023-06-07 20:33 UTC, edublancas commented
thanks for your contribution! @DaveOkpare