Snowflake guide
ploomber/jupysql pull request #591
Opened 2023-06-07 17:51 UTC by neelasha23

## Describe your changes
Snowflake integration guide

## Issue number

Closes #384 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-06-07 18:04 UTC, neelasha23 commented
I have added the guide, but the build is failing because of the dummy credentials. Initially I run the entire notebook, and after all the cell outputs were generated, I changed the connection parameters to dummy values:
```
engine = create_engine(
    URL(
        drivername="driver",
        user="user",
        password="password",
        account="account",
        database="database",
        role="role",
        schema="schema",
        warehouse="warehouse",
    )
)
```

However, the cells still try to execute and fails at `%sql engine`. 

Is there any other approach? Should we save these values as `readthedocs` public env variables and try to read those in the notebook? It would be read like `${env_variable_name}`, but this is specific to readthedocs and wont work on notebooks.

@edublancas

2023-06-07 20:31 UTC, edublancas requested changes
check comment above

2023-06-07 20:32 UTC, edublancas commented
btw, hide the connection string. instructions here: https://jupysql.ploomber.io/en/latest/howto.html#hide-connection-string

2023-06-08 16:45 UTC, edublancas approved these changes

2023-06-08 16:45 UTC, merged