alias0fix
ploomber/jupysql pull request #600
Opened 2023-06-08 16:24 UTC by AnirudhVIyer

## Describe your changes
Modified the set method in the Connection Class such that: if a connection with a descriptor exists, we check it's alias with the new alias argument.
## Issue number

Closes #532 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-06-09 18:10 UTC, edublancas requested changes
don't worry about the formatting changes (unsure about why it's happening but we can merge it)

just add some unit tests

2023-06-12 17:31 UTC, mehtamohit013 requested changes

2023-06-12 17:31 UTC, mehtamohit013 commented on src/sql/connection.py
> +                # if same alias found
@edublancas 
Please check whether this is a desired behavior. If yes, the logic looks good, and it is working on binder

2023-06-12 17:49 UTC, AnirudhVIyer commented on src/tests/test_connection.py
> +def test_new_connection_with_alias(ip_empty):
Sure ! Will add them

2023-06-12 20:34 UTC, anupam-tiwari commented
@AnirudhVIyer I think you removed your code

2023-06-12 20:35 UTC, AnirudhVIyer commented
> @AnirudhVIyer I think you removed your code

Yeah, an integration test is failing, trying to figure that out

2023-06-13 13:03 UTC, mehtamohit013 commented
@AnirudhVIyer 
It seems like other PR also have test failing. Make sure you merge with the master and test again

2023-06-14 00:48 UTC, edublancas commented
@tonykploomber: can you check the integration tests? looks like they're failing but this PR didn't change them. so perhaps some update in the docker image we're using?

2023-06-14 00:53 UTC, jinniw43805 commented
@edublancas 
This is something we found earlier, https://github.com/ploomber/jupysql/issues/614

2023-06-14 04:25 UTC, edublancas approved these changes

2023-06-14 04:26 UTC, merged

2023-06-14 04:26 UTC, edublancas commented
great work!

2023-06-14 16:53 UTC, jinniw43805 commented
@edublancas 
Any idea why [tests are skipped](https://github.com/ploomber/jupysql/actions/runs/5263047607/jobs/9512827286) when merged to master?

2023-06-14 17:10 UTC, mehtamohit013 commented
> @edublancas
> Any idea why [tests are skipped](https://github.com/ploomber/jupysql/actions/runs/5263047607/jobs/9512827286) when merged to master?

It may be due to my recently merged [PR](https://github.com/ploomber/jupysql/pull/598). In `check_doc` job, I am taking the `git diff` of the current branch with the `master` branch. This works great when running actions for a PR, but when merging, there is no `diff` between the `master` latest commit and the current branch i.e. `master` latest commit. May have to modify the test to run only for PR, and run all the tests when merging 

What is your opinion on the above issue? @edublancas @jinniw43805 @tonykploomber