Added `%sqlplot` tests
ploomber/jupysql pull request #628
Opened 2023-06-20 12:37 UTC by mehtamohit013

## Describe your changes
Added `%sqlplot` tests for boxplot and histogram
## Issue number

Closes #526 

## Checklist before requesting a review

- [X] Performed a self-review of my code
- [X] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [X] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [X] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--628.org.readthedocs.build/en/628/

2023-06-20 14:13 UTC, yafimvo requested changes
looks good.

@mehtamohit013 
Can we add more complex cases (a large number of bins (100/250/500), 2 plots, custom style, vertical/horizontal bar)? For this, we'll probably need a more complete dataset.

We can use these as references:

[plot](https://jupysql.ploomber.io/en/latest/api/magic-plot.html#id1)

[ggplot](https://jupysql.ploomber.io/en/latest/user-guide/ggplot.html)

2023-06-21 12:22 UTC, yafimvo requested changes
lgtm. Just one comment about the fixture and I think it's ready for merge.

2023-06-21 12:22 UTC, yafimvo commented on src/tests/test_magic_plot.py
> +def load_penguin(ip):
We use the same code in other places. Let's move this fixture to [conftest.py](https://github.com/ploomber/jupysql/blob/80743a5cecb9eb63efa134dbefba6570b9a9eaf1/src/tests/conftest.py).

2023-06-21 18:56 UTC, edublancas approved these changes

2023-06-21 18:56 UTC, merged