adds postgres instructions
ploomber/jupysql pull request #75
Opened 2023-01-10 04:00 UTC by edublancas

added two new sections showing how to get the postgres connector and how to connect to a running postgres instance

2023-01-10 14:03 UTC, yafimvo requested changes
Not sure if this is the right place for it or should we need to open a new issue.

It generates a horizontal scroller since the generated table is not contained in the page

![image](https://user-images.githubusercontent.com/103026689/211567545-9c4b06df-3dbb-4ec8-a459-9597f9cbf644.png)

2023-01-10 17:09 UTC, edublancas commented
> Not sure if this is the right place for it or should we need to open a new issue.
> 
> It generates a horizontal scroller since the generated table is not contained in the page

we're using a template, so the best place is here: https://github.com/executablebooks/sphinx-book-theme

2023-01-10 17:09 UTC, edublancas commented on doc/howto/postgres-connect.ipynb
> +    "You also need Docker installed and running do start the PostgreSQL instance."
fixed

2023-01-10 17:14 UTC, edublancas commented on doc/howto/postgres-install.md
> +pip install psycopg2-binary
the problem is that many people don't use conda (only pip), so I wanted to include the pip command. We're suggesting the `-binary` package, which shouldn't lead to issues. do you think we should also remove this reference?

> stall `psycopg2` is with the 

so they don't attempt to do "pip install psycopg2"?

2023-01-10 22:36 UTC, yafimvo commented on doc/howto/postgres-install.md
> +pip install psycopg2-binary
I think let's keep it and see if people are struggling with this. we give 2 alternatives so I think it's fair.

2023-01-10 22:37 UTC, yafimvo commented
> we're using a template, so the best place is here: https://github.com/executablebooks/sphinx-book-theme

I'll open an issue there

2023-01-11 02:01 UTC, edublancas commented on doc/howto/postgres-install.md
> +pip install psycopg2-binary
sure. are we good to merge then?

2023-01-11 05:43 UTC, yafimvo approved these changes

2023-01-11 05:43 UTC, merged