Resolve circular dependency
ploomber/jupysql pull request #787
Opened 2023-08-09 06:21 UTC by neelasha23

## Describe your changes
Move out functions accessing current connection to `inspect.py`

## Issue number

Closes #545

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-08-10 17:23 UTC, neelasha23 commented
Please review @edublancas

2023-08-14 22:49 UTC, edublancas commented
@neelasha23 I was about to review this but now I see that the tests are failing. what's the status? I guess there are merge conflicts due to recent changes in master?

2023-08-15 10:40 UTC, neelasha23 commented
> @neelasha23 I was about to review this but now I see that the tests are failing. what's the status? I guess there are merge conflicts due to recent changes in master?

Yes the snippets related tests started failing after I rebased. Fixed now. Please review.
@edublancas

2023-08-24 11:07 UTC, neelasha23 commented
Please review @edublancas

2023-08-24 23:22 UTC, edublancas requested changes
I just realized that I had reviewed this before but never submitted my observations  (they still appeared as "pending" but I think that means you'll never saw them), so I'm submitting them now.

there's a lot of changes in this PR so please write a brief description so I know what to expect. e.g., "moved functions from a.py, b.py, moved functions from c.py into a separate module"

i guess this is mostly moving stuff around and not adding any new stuff so please explain

2023-08-25 07:44 UTC, neelasha23 commented on src/sql/store_utils.py
> +from sql.store import store, get_dependents_for_key
yes when we add these functions in `store.py` the tests fail. In `isolate_tests` fixture there's the store is being cleared: `store.store = store.SQLStore()`. This is causing the store to become empty when running each test, although we are creating snippets again in the test.
I'm not sure exactly why this is happening but moving to a separate file solves the issue.

2023-08-25 07:45 UTC, neelasha23 commented on src/tests/test_inspect.py
> +@pytest.mark.parametrize(
yes these are old tests moved from `test_util.py`

2023-08-25 11:58 UTC, neelasha23 commented on src/tests/test_magic_cte.py
>  """
previously it was in `magic.py` due to the circular dependency. Now it's move to the error handler file and similar to the syntax error it displays descriptive error message + original db error. original db error was not there previously.

2023-08-26 12:45 UTC, neelasha23 commented on CHANGELOG.md
> +* [Fix] Resolve circular dependency issue occurring due to multiple imports in `util.py`
[fixed](https://github.com/ploomber/jupysql/pull/787/commits/10a987fd245032cae516c5719ec4ebf5c5f77d32)

2023-08-26 12:46 UTC, neelasha23 commented on CHANGELOG.md
> +* [Fix] Handling of DuckDB `Parser Error` and `pyodbc.ProgrammingError`
[fixed](https://github.com/ploomber/jupysql/pull/787/commits/10a987fd245032cae516c5719ec4ebf5c5f77d32)

2023-08-26 12:46 UTC, neelasha23 commented on src/tests/test_inspect.py
> +EXPECTED_SUGGESTIONS_MESSAGE = "Did you mean :"
[fixed](https://github.com/ploomber/jupysql/pull/787/commits/10a987fd245032cae516c5719ec4ebf5c5f77d32)

2023-08-26 17:22 UTC, neelasha23 commented on src/sql/connection/connection.py
> +            ErrorHandler(e).handle_exception()
[fixed](https://github.com/ploomber/jupysql/pull/787/commits/587279506d14c0d97a70f41c0efab07f7029eb7c)

2023-08-26 17:40 UTC, neelasha23 commented
Addressed your comments and updated the PR description @edublancas

2023-08-28 21:45 UTC, edublancas approved these changes

2023-08-28 21:45 UTC, merged

2023-08-28 21:48 UTC, edublancas commented
@neelasha23 good work!

when writing your initial comment, write each issue on a separate line:

closes #X
closes #Y

because if you do

closes #X #Y

github won't close both issues