Clean error msg in case of boxplot
ploomber/jupysql pull request #829
Opened 2023-08-24 17:35 UTC by mehtamohit013

## Describe your changes
Clean error msg in case of non-numeric column for boxplot
## Issue number

Closes #478 

## Checklist before requesting a review

- [X] Performed a self-review of my code
- [X] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [X] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [X] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--829.org.readthedocs.build/en/829/

2023-08-24 20:53 UTC, mehtamohit013 commented
@edublancas 
Ready for review and merge

2023-08-28 20:08 UTC, edublancas requested changes

2023-08-28 20:08 UTC, edublancas commented on src/sql/plot.py
> +    set_ticks = ax.set_xticks if vert else ax.set_yticks
is this some unrelated bug that you fixed? doesn't seem related to the PR

2023-08-28 20:08 UTC, edublancas commented on src/sql/stats.py
> +        ) and msg_numeric_type in e.orig.args[0]:
comment on when each one is raised, I'm guessing one is for postgres and another one for duckdb?

2023-08-28 20:08 UTC, edublancas commented on src/sql/stats.py
> +            )
when raising an exception inside another exception use `raise Exception(...) from e` to chain them

2023-09-06 01:21 UTC, closed without merging