Add integration chDB doc
ploomber/jupysql pull request #857
Opened 2023-09-04 13:43 UTC by nmreadelf

Closes https://github.com/chdb-io/chdb/issues/15

2023-09-04 17:20 UTC, neelasha23 commented
Docs build is failing @nmreadelf

2023-09-05 00:14 UTC, nmreadelf commented
> Docs build is failing @nmreadelf

thx, i fixed

2023-09-05 01:03 UTC, edublancas requested changes
the documentation build is failing

you need to add your doc here: https://github.com/ploomber/jupysql/blob/master/doc/_toc.yml

then, you'll need to add chdb here:

https://github.com/ploomber/jupysql/blob/master/doc/environment.yml
https://github.com/ploomber/jupysql/blob/master/doc/environment.lock.yml

2023-09-05 01:03 UTC, edublancas commented on doc/integrations/chdb.md
> +```
looks like this section is showing how to add a new connection, I think we can delete it. we already have documentation on how to manage connections

2023-09-05 01:03 UTC, edublancas commented on doc/integrations/chdb.md
> +```
we can delete this as well

2023-09-05 01:03 UTC, edublancas commented on CHANGELOG.md
> +* [Feature] Add chDB integration doc
```suggestion
* [Doc] Add chDB integration tutorial
```

feel free to add your github username at the end

2023-09-05 02:24 UTC, nmreadelf commented on doc/integrations/chdb.md
> +```
thx

2023-09-05 02:28 UTC, nmreadelf commented
> the documentation build is failing
> 
> you need to add your doc here: https://github.com/ploomber/jupysql/blob/master/doc/_toc.yml
> 
> then, you'll need to add chdb here:
> 
> https://github.com/ploomber/jupysql/blob/master/doc/environment.yml https://github.com/ploomber/jupysql/blob/master/doc/environment.lock.yml

thx, fixed

2023-09-05 02:59 UTC, merged

2023-09-05 03:00 UTC, edublancas commented
awesome, thanks! @nmreadelf feel free to come back to add new stuff to the tutorial. chDB is an exciting project!